### ISSUE TITLE
H5parm exception when running DDEcal

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/DP3#151]
Hi,

I recently encounter an error in DPPP when trying to run DDEcal on CEP3. No matter what I do (changing basic parameters or whatever) DPPP always crashes with the following error:

```
2019-05-29 08:59:35 WARNING node.lof009.control.lofar.executable_args.L228163_SB000_uv.dppp_124701747t_124MHz.msdpppconcat: /opt/cep/lofim/daily/Tue/lofar_build/install/gnucxx11_opt//bin/NDPPP stderr: 
**** uncaught exception ****

Backtrace follows:
#0  0x7fc4f5a9fb0f in LOFAR::Exception::terminate() at Exception.cc:89
#1  0x7fc4ee570946 in std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:0
#2  0x7fc4ee570973 in std::terminate() at ??:0
#3  0x7fc4ee570b93 in __cxa_throw at ??:0
#4  0x7fc4f0f1d52a in H5::DataSet::write(void const*, H5::DataType const&, H5::DataSpace const&, H5::DataSpace const&, H5::DSetMemXferPropList const&) const at ??:0
#5  0x7fc4f61f0e70 in LOFAR::H5Parm::addSources(std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > > const&) at H5Parm.cc:119
#6  0x7fc4e824931f in LOFAR::DPPP::DDECal::updateInfo(LOFAR::DPPP::DPInfo const&) at DDECal.cc:347
#7  0x7fc4f60f2fc0 in LOFAR::DPPP::DPStep::setInfo(LOFAR::DPPP::DPInfo const&) at DPStep.cc:38
#8  0x7fc4f60eac9f in LOFAR::DPPP::DPRun::execute(std::string const&, int, char**) at DPRun.cc:137
#9  0x4054a8 in main at NDPPP.cc:88
terminate called after throwing an instance of 'H5::DataSetIException'
```

I have not encountered such an issue before. The minimal example to reproduce the error is like this:

```
msin=L228163_SB000_uv.dppp_124701747t_118MHz.msdpppconcat
msin.datacolumn=SMOOTHED_DATA
msout=L228163_SB000_uv.dppp_124701747t_118MHz.msdpppconcat
steps=[gaincal]
gaincal.type=ddecal
gaincal.mode=phaseonly
gaincal.sourcedb=target.make_sourcedb_target
gaincal.h5parm=L228163_SB000_uv.dppp_124701747t_118MHz.msdpppconcat.h5
```

Changing the mode to `diagonal` or `phaseonly` does not change anything. I don't get this error and everything runs fine if I just use the old `gaincal` solve, even if I write the solutions out to an `h5parm`.

**Comment by aroffringa** [comment]
Thanks @adrabent . @tammojan , is this something you can fix?

**Comment by tammojan** [comment]
I cannot reproduce this issue. On CEP3, the current best way to get DPPP DDECal running is:
```
module load dp3
```
Unfortunately this leads to a library error, which is solved by running `export LD_LIBRARY_PATH=/opt/cep/LOFARBeam/LOFARBeam-20190206/lib/:$LD_LIBRARY_PATH`.

**Comment by adrabent** [comment]
I reloaded the modules on CEP3 and the issue has disappeared and I also can not reproduce this error anymore.

**Comment by aroffringa** [comment]
Ok, good to know, thanks @adrabent !
