### ISSUE TITLE
segfault when pre-applying multiple h5parms

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#167]
I get a segfault when I try to preapply 2 h5parms in a dde solve. Might it be because the time-resolution of the two h5parms I want to apply are different?

This is my command:

DPPP /home/fdg/scripts/LiLF/parsets/LOFAR_dd-incr/DPPP-solTEC.parset 
msin=mss-dd/TC08.MS 
sol.applycal.steps=[myapplycal1,myapplycal2] 
sol.applycal.myapplycal1.correction=tec000 
sol.applycal.myapplycal2.correction=tec000 
sol.applycal.myapplycal1.parmdb=ddcal/solutions/cal-core-c0.h5 
sol.applycal.myapplycal2.parmdb=ddcal/solutions/cal-remote-c0.h5 
sol.solint=10 sol.nchan=4 sol.h5parm=mss-dd/TC08.MS/cal-remote2-c0.h5 
sol.sourcedb=ddcal/skymodels/skymodel00_cluster.skydb

**Comment by aroffringa** [comment]
Can you make a gdb stack backtrace?

**Comment by tammojan** [comment]
Hi Francesco, could you point me to the data you're using?

**Comment by tammojan** [comment]
Never mind, found them.

**Comment by tammojan** [comment]
I have reproduced the segfault and am working on this.

**Comment by tammojan** [comment]
For reference; the issue does not occur when using one of the two applycal's. The stacktrace points to HDF5:

```
#0  0x00007ffff77c0416 in H5SL_remove () at /lib64/libhdf5.so.8
#1  0x00007ffff769477e in H5FO_delete () at /lib64/libhdf5.so.8
#2  0x00007ffff763ff3d in H5D_close () at /lib64/libhdf5.so.8
#3  0x00007ffff77078bd in H5I_dec_ref () at /lib64/libhdf5.so.8
#4  0x00007ffff77079b5 in H5I_dec_app_ref () at /lib64/libhdf5.so.8
#5  0x00007ffff7707b83 in H5I_dec_app_ref_always_close () at /lib64/libhdf5.so.8
#6  0x00007ffff761b58e in H5Dclose () at /lib64/libhdf5.so.8
#7  0x00007ffff7bc0838 in H5::DataSet::close() () at /lib64/libhdf5_cpp.so.8
#8  0x00007ffff7bc2316 in H5::DataSet::~DataSet() () at /lib64/libhdf5_cpp.so.8
#9  0x0000000000550c44 in DP3::H5Parm::SolTab::getRealAxis(std::string const&) const (this=this@entry=0xaaabf8, axisname="time")
    at /home/dijkema/opt/DP3/src/DPPP/SolTab.cc:505
#10 0x000000000055245d in DP3::H5Parm::SolTab::getValuesOrWeights(std::string const&, std::string const&, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > const&, unsigned int, unsigned int, bool) (this=this@entry=0xaaabf8, valOrWeight="weight", antName="CS301LBA", times=std::vector of length 10, capacity 10 = {...}, freqs=std::vector of length 976, capacity 976 = {...}, pol=pol@entry=0, dir=dir@entry=5, nearest=nearest@entry=true) at /home/dijkema/opt/DP3/src/DPPP/SolTab.cc:250
#11 0x00000000005414c5 in DP3::DPPP::OneApplyCal::updateParms(double, std::mutex*) (this=this@entry=
    0xaa95a0, bufStartTime=5022559329.9926014, hdf5Mutex=hdf5Mutex@entry=0x7fffffffbaa0)
    at /home/dijkema/opt/DP3/src/DPPP/OneApplyCal.cc:553
#12 0x000000000054425b in DP3::DPPP::OneApplyCal::process(DP3::DPPP::DPBuffer const&, std::mutex*) (this=0xaa95a0, bufin=..., hdf5Mutex=hdf5Mutex@entry=0x7fffffffbaa0) at /home/dijkema/opt/DP3/src/DPPP/OneApplyCal.cc:389
#13 0x000000000048a767 in DP3::DPPP::ApplyCal::process(DP3::DPPP::DPBuffer const&, std::mutex*) (this=this@entry=0xae28c8, bufin=..., hdf5Mutex=0x7fffffffbaa0) at /home/dijkema/opt/DP3/src/DPPP/ApplyCal.cc:129
#14 0x0000000000537f3a in DP3::DPPP::Predict::process(DP3::DPPP::DPBuffer const&) (buffer=..., this=0xae28c8)
    at /home/dijkema/opt/DP3/src/DPPP/ApplyCal.h:65
#15 0x0000000000537f3a in DP3::DPPP::Predict::process(DP3::DPPP::DPBuffer const&) (this=0xae12d0, bufin=...)
    at /home/dijkema/opt/DP3/src/DPPP/Predict.cc:438
#16 0x000000000060feda in std::_Function_handler<void(long unsigned int), std::_Bind<DP3::DPPP::DDECal::process(const DP3::DPPP::DPBuffer&)::__lambda2(long unsigned int, std::_Placeholder<1>)> >::_M_invoke(const std::_Any_data &, unsigned long) (dir=5, __closure=0xbd4fd0) at /home/dijkema/opt/DP3/src/DDECal/DDECal.cc:910
#17 0x000000000060feda in std::_Function_handler<void(long unsigned int), std::_Bind<DP3::DPPP::DDECal::process(const DP3::DPPP::DPBuffer&)::__lambda2(long unsigned int, std::_Placeholder<1>)> >::_M_invoke(const std::_Any_data &, unsigned long) (__args=<optimized out>, this=0xbd4fd0) at /usr/include/c++/4.8.2/functional:1296
#18 0x000000000060feda in std::_Function_handler<void(long unsigned int), std::_Bind<DP3::DPPP::DDECal::process(const DP3::DPPP::DPBuffer&)::__lambda2(long unsigned int, std::_Placeholder<1>)> >::_M_invoke(const std::_Any_data &, unsigned long) (this=0xbd4fd0)
    at /usr/include/c++/4.8.2/functional:1355
#19 0x000000000060feda in std::_Function_handler<void(long unsigned int), std::_Bind<DP3::DPPP::DDECal::process(const DP3::DPPP::DPBuffer&)::__lambda2(long unsigned int, std::_Placeholder<1>)> >::_M_invoke(const std::_Any_data &, unsigned long) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/4.8.2/functional:2071
#20 0x00000000005258d2 in DP3::ThreadPool::threadFunc(unsigned long) (__args#0=8, this=0x7fff70e6c140)
    at /usr/include/c++/4.8.2/functional:2471
#21 0x00000000005258d2 in DP3::ThreadPool::threadFunc(unsigned long) (this=0xa34660, threadId=8)
    at /home/dijkema/opt/DP3/src/DPPP/../Common/ThreadPool.h:147
#22 0x00007fffec7b9230 in  () at /lib64/libstdc++.so.6
#23 0x00007fffeca14dc5 in start_thread () at /lib64/libpthread.so.0
#24 0x00007fffec22476d in clone () at /lib64/libc.so.6
```
