### ISSUE TITLE
Broken MS after [CR]S*& baseline remove

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/DP3#333]
Using DP3 master I did:
```
msin                                =   /storage/akurek/N4449_mozaik/L258201_tests_small/3C196/L258197_SB000_uv.dppp.MS
msin.datacolumn                     =   DATA
msin.baseline                       =   [CR]S*&
msin.autoweight                     =   False
msout                               =   test.MS
msout.datacolumn                    =   DATA
msout.writefullresflag              =   False
msout.overwrite                     =   True
msout.storagemanager                =   "Dysco"
msout.storagemanager.databitrate    =   0
steps                               =   [filter]
filter.type                         =   filter
filter.baseline                     =   [CR]S*&
filter.remove                       =   true
```
and later as @mhardcastle suggested:
```
import pyrap.tables as pt
t=pt.table('/storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA')
print(t[:]['NAME'])

for i in range(len(t)):
    print(i,t[i]['NAME'])
```
and Im getting:
```
Successful readonly open of default-locked table /storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA: 10 columns, 69 rows
Traceback (most recent call last):
File "first.py", line 3, in
print(t[:]['NAME'])
File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 466, in getitem
return self._row._getitem(key, self.nrows())
File "/usr/lib/python3/dist-packages/casacore/tables/tablerow.py", line 73, in _getitem
result.append(self.get(rownr))
File "/usr/lib/python3/dist-packages/casacore/tables/tablerow.py", line 50, in get
return self._get(rownr)
RuntimeError: SSMIndex::getIndex - access to non-existing row 62 in column OFFSET of table /storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA
```
(this thread is copied form https://github.com/lofar-astron/prefactor/issues/292#issuecomment-944874566 )

**Comment by tammojan** [comment]
I'm sorry, but I can't reproduce this with the latest DP3 master (also I'm not aware of any recent changes that could have influenced this code path). Here's the command I used:
```
#!/usr/bin/bash

set -e

cat <<EOT >> DPPP.txt
msin=temp.MS
msout=temp-filtered.MS
msout.overwrite=True
steps=[filter]
filter.remove=True
filter.baseline='CS*&'
msout.storagemanager=Dysco
msout.storagemanager.databitrate=0
EOT

DP3 DPPP.txt
echo "Done with DP3"

python3 - <<EOF
import casacore.tables as pt

t = pt.table("temp-filtered.MS/ANTENNA")

for i in range(len(t)):
  print(i, t[i]['NAME'])
EOF
```
I'll try to have a look at the MSs on the Herts cluster.

**Comment by tammojan** [comment]
We had a look at the MS on the Herts cluster, and reproduced the behavior you report. However, the measurement seems to be broken already before we run DP3 on it:
```
taql 'select * from L258201_SB244_uv.dppp_125C46F7At_121MHz.pre-cal.ms::ANTENNA`
```
already gives the error. Looking at the history table of this measurement set, no DP3 filter operation was run on it. Did some other (python) program try to remove stations?
```
taql ' select * from L258201_SB244_uv.dppp_125C46F7At_121MHz.pre-cal.ms/HISTORY'
```
