### ISSUE TITLE
Problem writing new MS with column not named "DATA"

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/DP3#84]
I am trying to copy a column to a new MS file with the following command:

`DPPP msin=L658734_SB088_uv.ndppp_prep_cal msout=test.ms steps=[] msin.datacolumn=CORRECTED_DATA`

but get the error:

```
 copying info and subtables ...

std exception detected: Table column CORRECTED_DATA is unknown
```

I verified with casacore.tables that the CORRECTED_DATA column is definitely there. gdb suggests the problem is in MSWriter::createMS:

```
Thread 1 "DPPP" hit Catchpoint 1 (exception thrown), 0x00007ffff1ea28bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff1ea28bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff5c2b00d in casa::SetupNewTableRep::setup() () from #2  0x00007ffff5c2b6a4 in casa::SetupNewTableRep::SetupNewTableRep(casa::String const&, casa::TableDesc const&, casa::Table::TableOption, casa::StorageOption const&) ()
   from /home/lofar/opt4/casacore/lib/libcasa_tables.so.2
#3  0x00007ffff5c2b8d0 in casa::SetupNewTable::SetupNewTable(casa::String const&, casa::TableDesc const&, casa::Table::TableOption, casa::StorageOption const&) ()
   from /home/lofar/opt4/casacore/lib/libcasa_tables.so.2
#4  0x00000000004bee5c in DP3::DPPP::MSWriter::createMS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DP3::DPPP::DPInfo const&, unsigned int, unsigned int) ()
#5  0x00000000004bdd32 in DP3::DPPP::MSWriter::updateInfo(DP3::DPPP::DPInfo const&) ()
#6  0x000000000046830b in DP3::DPPP::DPStep::setInfo(DP3::DPPP::DPInfo const&) ()
#7  0x0000000000468351 in DP3::DPPP::DPStep::setInfo(DP3::DPPP::DPInfo const&) ()
#8  0x0000000000468351 in DP3::DPPP::DPStep::setInfo(DP3::DPPP::DPInfo const&) ()
#9  0x000000000045752c in DP3::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) ()
#10 0x0000000000454ece in main ()
```

It works fine if I set `msin.datacolumn=DATA`, but not for any other existing column name.

**Comment by aroffringa** [comment]
Thanks for the useful report @darafferty , somewhere in the implementation of #60 I assumed that the new column always had the name of the input column. I've now fixed this in the pull request.
